config/routes.rb
Rails.application.routes.draw do
  resources :downloads
  resources :devlogs
  resources :pictures
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resource :home
  resources :devlogs
  get "/drafts", to: "devlogs#drafts"

  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/devlog.rb
class Devlog < ApplicationRecord
  belongs_to :user
end

app/models/download.rb
class Download < ApplicationRecord
  has_one_attached :file
end

app/models/picture.rb
class Picture < ApplicationRecord
  has_one_attached :file
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  has_many :devlogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery
end

app/controllers/devlogs_controller.rb
class DevlogsController < ApplicationController

  def index
    authorize Devlog.new
    @devlogs = policy_scope(Devlog.all).order(created_at: :desc)

    if params[:y].present? && params[:m].present?
      @devlogs = @devlogs.where('extract(year from created_at) = ?', params[:y]).where('extract(month from created_at) = ?', params[:m])
    end

    @more_logs = policy_scope(Devlog.all).order(created_at: :desc).pluck("extract(month from created_at)", "extract(year from created_at)").uniq
  end

  def show
    @devlog = policy_scope(Devlog.find_by(id: params[:id]))
    @more_logs = policy_scope(Devlog.all).order(created_at: :desc).pluck("extract(month from created_at)", "extract(year from created_at)").uniq
    authorize @devlog
  end

  def drafts
    authorize Devlog.new
    @devlogs = Devlog.where(public: false).order(created_at: :desc)
  end

  def new
    authorize Devlog.new
    @pictures = Picture.all.order(created_at: :desc).limit(20)
  end

  def create
    devlog = Devlog.new
    devlog.assign_attributes(params.require(:devlog).permit([
      :title,
      :short_description,
      :body,
      :user_id
    ]))
    authorize devlog
    if params[:commit] == "Save"
      devlog.public = false
    else
      devlog.public = true
    end
    devlog.save!

    redirect_to devlog_path(devlog)
  end

  def edit
    @devlog = Devlog.find_by(id: params[:id])
    authorize @devlog
  end

  def update
    devlog = Devlog.find_by(id: params[:id])
    devlog.assign_attributes(params.require(:devlog).permit([
      :title,
      :short_description,
      :body,
      :user_id,
      :public
    ]))
    authorize devlog
    if params[:commit] == "Publish!" || params[:commit] == "Update!"
      devlog.public = true
    end
    devlog.save!

    redirect_to devlog_path(devlog)
  end

  def destroy
    devlog = Devlog.find_by(id: params[:id])
    authorize devlog
    devlog.destroy!

    redirect_to devlogs_path
  end

end

app/controllers/downloads_controller.rb
class DownloadsController < ApplicationController

  def index
    #authorize Download.new
    @downloads = Download.all.order(created_at: :desc)

  end

  def new
    # authorize Download.new

  end

  def create
    download = Download.new
    download.assign_attributes(params.require(:download).permit([
      :name,
      :file,
      :kind,
      :file_size,
      :description
    ]))
    # authorize download
    download.save!

    redirect_to downloads_path
  end

  def edit
    @download = Download.find_by(id: params[:id])
    # authorize @download
  end

  def update
    download = Download.find_by(id: params[:id])
    download.assign_attributes(params.require(:download).permit([
      :name,
      :file,
      :kind,
      :file_size,
      :description
    ]))
    # authorize download
    download.save!

    redirect_to downloads_path
  end

  def destroy
    download = Download.find_by(id: params[:id])
    # authorize download
    download.destroy!

    redirect_to downloads_path
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @last_log = Devlog.where(public: true).order(:created_at).last
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

  def create
    picture = Picture.new
    picture.assign_attributes(params.require(:picture).permit([
    ]))
    picture.file.attach(params[:picture][:file])
    picture.save!
    @pictures = Picture.all.order(created_at: :desc).limit(20)
    respond_to do |format|
      format.html
      format.js { render partial: "pictures/loadPictures", :layout => false }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = CustomRender.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

class CustomRender < Redcarpet::Render::HTML
  def image(link, title, alt_text)
    if link.include?('=youtube')
      %(<div style='text-align: center'><iframe src='https://www.youtube.com/embed/#{link.split('=youtube')[1].split('v=')[1]}' frameborder='0' allowfullscreen width='640px' style='max-width: 100%' height='360px'></iframe></div>)
    else
      %(<img src="#{link}" width="100%" height="100%" alt="#{alt_text} />")
    end
  end
end

app/helpers/devlogs_helper.rb
module DevlogsHelper
end

app/helpers/downloads_helper.rb
module DownloadsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/devlogs/_more_logs.html.slim
.card
  .card-content
    .card-title
      | More logs

    h5
      = link_to "All logs", devlogs_path
    hr width="50%"
    - @more_logs.each do |date|
      h5
        = link_to "#{Date::MONTHNAMES[date[0].to_i]} #{date[1].to_i}", devlogs_path(y: date[1].to_i, m: date[0].to_i)

app/views/devlogs/drafts.html.slim
#navbar-padder
.container
  .center-align
    h2.white-text
      | Drafts
  .row
    .col.s4.offset-s4.center-align
      = link_to "NEW LOG", new_devlog_path, class: "btn-flat outline-btn stormy-blue full-width"

  .row
    .col.s12
      .card
        .card-content
          - @devlogs.each do |log|
            .card
              .card-content
                .card-title
                  = link_to log.title, devlog_path(log)
                .right
                  - if current_user
                    = link_to "Edit", edit_devlog_path(log), class: "btn-flat outline-btn stormy-blue full-width"

                blockquote
                  = log.short_description
                .right
                  = "#{log.user.email} - #{log.created_at.strftime("%B %d, %Y")}"
                br
                br
                .row
                  .col.s6.offset-s3
                    = form_for log, method: :put do |ff|
                      = ff.hidden_field :public, value: true
                      = ff.submit "Publish", class: "btn-flat outline-btn stormy-blue full-width"

app/views/devlogs/edit.html.slim
#navbar-padder
.container
  .card
    .card-content
      .card-title
        | Edit log
        - if @devlog.public == false
          br
          .red-text
            | NOT PUBLISHED

      blockquote
        | Use markdown to create your article
        br
        | Check out this&nbsp;
        a href="https://stackedit.io/"
          | markdown editor
        | !
        br
        | You can embed YouTube videos with ![Image](=youtube http://link/to/video)
      br
      br
      br
      = form_for @devlog, method: :put do |f|
        = f.hidden_field :user_id, value: current_user.id

        .field style="width: 50%"
          = f.label :title, "Title"
          = f.text_field :title, class: "input"

        br
        br
        .field style="width: 50%"
          = f.label :short_description, "Introduction"
          = f.text_area :short_description, class: "materialize-textarea"

        br
        br
        .field
          = f.label :body, "Log"
          = f.text_area :body, class: "materialize-textarea"

        br
        br
        .row
          .col.s6.offset-s3
            - if @devlog.public == false
              = f.submit "Save", class: "btn-flat outline-btn stormy-blue full-width"
              br
              br
              = f.submit "Publish!", class: "btn-flat outline-btn stormy-blue full-width"
            - else
              = f.hidden_field :public, value: true
              = f.submit "Update!", class: "btn-flat outline-btn stormy-blue full-width"
              br
              br
              = form_for @devlog, method: :put do |ff|
                = ff.hidden_field :public, value: false
                = ff.submit "Unpublish", class: "btn-flat outline-btn stormy-blue full-width"



      br
      br
      .row
        .col.s6.offset-s3
          = button_to "Delete Log", devlog_path(@devlog), method: :delete, class: "btn-flat danger-outline-btn red-text full-width"

app/views/devlogs/index.html.slim
#navbar-padder
.container
  - if current_user
    .row
      .col.s3.offset-s3.center-align
        = link_to "NEW LOG", new_devlog_path, class: "btn-flat outline-btn stormy-blue full-width"
      .col.s3.center-align
        = link_to "DRAFTS", drafts_path, class: "btn-flat outline-btn stormy-blue full-width"

  .row
    .col.s9
      .card
        .card-content
          - @devlogs.each do |log|
            .card
              .card-content
                .card-title
                  = link_to log.title, devlog_path(log)
                .right
                  - if current_user
                    = link_to "Edit", edit_devlog_path(log), class: "btn-flat outline-btn stormy-blue full-width"

                blockquote
                  = log.short_description
                .right
                  = "#{log.user.name} - #{log.created_at.strftime("%B %d, %Y")}"
                br

    .col.s3
      = render partial: "more_logs"

app/views/devlogs/new.html.slim
#navbar-padder
.container
  .row
    .col.s9
      .card
        .card-content
          .card-title
            | Create a new log
          blockquote
            | Use markdown to create your article
            br
            | Check out this&nbsp;
            a href="https://stackedit.io/"
              | markdown editor
            | !
            br
            | You can embed YouTube videos with ![Image](=youtube http://link/to/video)
          br
          br
          br
          = form_for Devlog.new do |f|
            = f.hidden_field :user_id, value: current_user.id

            .field style="width: 50%"
              = f.label :title, "Title"
              = f.text_field :title, class: "input"

            br
            br
            .field style="width: 50%"
              = f.label :short_description, "Introduction"
              = f.text_area :short_description, class: "materialize-textarea"

            br
            br
            .field
              = f.label :body, "Log"
              = f.text_area :body, class: "materialize-textarea"

            br
            br
            .row
              .col.s6.offset-s3
                = f.submit "Save", class: "btn-flat outline-btn stormy-blue full-width"
                br
                br
                br
                = f.submit "Publish!", class: "btn-flat outline-btn stormy-blue full-width"

          br
          br
    .col.s3
      .card
        .card-content
          = form_for Picture.new, :remote => true do |ff|
            .file-field.input-field
              .btn-flat.outline-btn.stormy-blue.full-width.center-align
                span
                  | Image
                = ff.file_field :file, class: "file-field input-field"
              .file-path-wrapper
                input class="file-path validate" type="text" placeholder="Upload one file" id="text_part"
            .center-align
              = ff.submit "Add image", class: "btn-flat outline-btn"
          br
          .center-align
            hr width="50%"
          br
          #pic_list
            - @pictures.each do |picture|
              = image_tag picture.file, style: "width: 100%", id: "IMG_TAG+#{url_for(picture.file.attachment)}"


javascript:
  $('input[type=file]').change(function () {
    if (this.files.length > 1)
      document.getElementById("text_part").value = "Multi";
    else
      document.getElementById("text_part").value = this.files[0].name
  });

  $('img[id^="IMG_TAG+"]').click(function () {
    let body = document.getElementById("devlog_body");
    body.value = body.value + `![Image](${this.id.split("IMG_TAG+")[1]} =100x100)`;
  });

app/views/devlogs/show.html.slim
#navbar-padder
.container
  .row
    .col.s9
      .card
        .card-content
          .card-title
            = @devlog.title
            - if @devlog.public == false
              br
              .red-text
                | NOT PUBLISHED
          .right
            - if current_user
              = link_to "Edit", edit_devlog_path(@devlog), class: "btn-flat outline-btn stormy-blue full-width"

          blockquote
            = @devlog.short_description
          .right
            = "#{@devlog.user.email} - #{@devlog.created_at.strftime("%B %d, %Y")}"
          br
          br
          br
          = markdown(@devlog.body)
    .col.s3
      = render partial: "more_logs"

app/views/downloads/edit.html.slim
#navbar-padder
.container
  .card
    .card-content
      .card-title
        | Update a new downloadable file
      br
      br
      br
      = form_for @download, method: :put do |f|

        .field style="width: 50%"
          = f.label :name, "Name"
          = f.text_field :name, class: "input"

        br
        br
        .field style="width: 50%"
          = f.label :description, "Description"
          = f.text_area :description, class: "materialize-textarea"

        br
        br
        .field style="width: 50%"
          = f.label :kind, "Type (audio, video, doc...)"
          = f.text_field :kind, class: "input"

        br
        = f.file_field :file, class: "file-field input-field"
        br


        br
        br
        .row
          .col.s6.offset-s3
            = f.submit "Publish!", class: "btn-flat outline-btn stormy-blue full-width"



            br
            br
            br
            = button_to "Delete File", download_path(@download), method: :delete, class: "btn-flat danger-outline-btn red-text full-width"

app/views/downloads/index.html.slim
#navbar-padder
.container
  - if current_user
    .row
      .col.s4.offset-s4.center-align
        = link_to "NEW FILE", new_download_path, class: "btn-flat outline-btn stormy-blue full-width"

  .row
    .col.s8.offset-s2
      - @downloads.each do |download|
        .card
          .card-content
            .card-title
              = download.name
              .right
                - if current_user
                  = link_to "Edit", edit_download_path(download), class: "btn-flat outline-btn stormy-blue full-width"
            = "#{download.kind.capitalize}, #{Filesize.from("#{download.file_size} B").pretty}"
            blockquote
              = download.description
              .right
                = link_to "Download", download.file, class: "btn-flat outline-btn stormy-blue full-width"

app/views/downloads/new.html.slim
#navbar-padder
.container
  .card
    .card-content
      .card-title
        | Create a new downloadable file
      br
      br
      br
      = form_for Download.new do |f|

        .field style="width: 50%"
          = f.label :name, "Name"
          = f.text_field :name, class: "input"

        br
        br
        .field style="width: 50%"
          = f.label :description, "Description"
          = f.text_area :description, class: "materialize-textarea"

        br
        br
        .field style="width: 50%"
          = f.label :kind, "Type (audio, video, doc...)"
          = f.text_field :kind, class: "input"

        br
        br
        .file-field.input-field style="width: 50%"
          .btn-flat.outline-btn.stormy-blue.full-width.center-align
            span
              | File
            = f.file_field :file, class: "file-field input-field", direct_upload: true
          .file-path-wrapper
            input class="file-path validate" type="text" placeholder="Upload one file" id="text_part"
        = f.hidden_field :file_size, value: 0
        br
        br
        .row
          .col.s6.offset-s3
            = f.submit "Publish!", class: "btn-flat outline-btn stormy-blue full-width"


javascript:
  $('input[type=file]').change(function () {
    if (this.files.length > 1)
      document.getElementById("text_part").value = "Multi";
    else {
      document.getElementById("text_part").value = this.files[0].name
      document.getElementById("download_file_size").value = this.files[0].size
    }
  });

app/views/downloads/show.html.slim
#navbar-padder
.container
  .row
    .col.s9
      .card
        .card-content
          .card-title
            = @devlog.title
          .right
            - if current_user
              = link_to "Edit", edit_devlog_path(@devlog), class: "btn-flat outline-btn stormy-blue full-width"

          blockquote
            = @devlog.short_description
          .right
            = "#{@devlog.user.email} - #{@devlog.created_at.strftime("%B %d, %Y")}"
          br
          br
          br
          = markdown(@devlog.body)
    .col.s3
      = render partial: "more_logs"

app/views/home/index.html.slim
#navbar-padder
.container
  /= video_tag "trailer.mp4", mute: "mute", class: "video", id: "trailer", controls: ""
  = image_tag "lake.png", class: "video"
  .row
    .col.s6.offset-s3
      .card.semi-transparent-card
        .card-content
          .card-title.center-align
            h2.is-light-weight
              | Latest news

              hr width="50%"
          - if @last_log.present?
            h3.is-light-weight
              = "> #{@last_log.title}"
            h5.is-light-weight
              = "by #{@last_log.user.name}"
              .right
                = "#{@last_log.created_at.strftime("%B %d, %Y")}"

            blockquote.flow-text
              = @last_log.short_description

            .row
              .col.s6.offset-s3
                = button_to "See article", devlog_path(@last_log), class: "btn-flat outline-btn full-width", method: :get


javascript:
  var vid = document.getElementById("trailer");
  if (vid) {
    vid.addEventListener("ended", function() {
      vid.remove();
    })
  }

app/views/layouts/_nav.html.slim
#top-navbar-padder
nav.less-dark-back-alpha
  .nav-wrapper.container
    a.brand-logo.is-fun-text.white-text href=root_path
      | Plain of glittering stone
    ul.right.hide-on-med-and-down
      li
        = link_to "Dev Blog", devlogs_path, class: "is-fun-text is-30px white-text"
      li
        = link_to "Downloads", downloads_path, class: "is-fun-text is-30px white-text"
      li
        | &nbsp;&nbsp;&nbsp;&nbsp;
      - if current_user.present?
        li
          = link_to "Log out", destroy_user_session_path, method: :delete, class: "is-fun-text is-30px white-text"
      - else
        li
          = link_to "Log in", new_user_session_path, class: "is-fun-text is-30px white-text"

    ul.hide-on-large-only.topnav id="mobile-demo"
      li
        = link_to "Dev Blog", devlogs_path, class: "is-fun-text is-30px white-text"
    ul.right.hide-on-large-only.topnav id="mobile-demo"
      li
        = link_to "Downloads", downloads_path, class: "is-fun-text is-30px white-text"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Plain of glittering stone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="dark-back">
    <%= render partial: 'layouts/nav' %>
    <%= yield %>
  </body>
</html>

app/views/pictures/_loadPictures.js.erb
var block = [];

<% @pictures.each do |picture| %>
  block.push("<img src=\"<%= url_for(picture.file.attachment) %>\" width=\"100%\" id=\"<%= "IMG_TAG+" + url_for(picture.file.attachment) %>\" />")
<% end %>

document.getElementById("pic_list").innerHTML = block.join("<br />")

$('img[id^="IMG_TAG+"]').click(function () {
  let body = document.getElementById("devlog_body");
  body.value = body.value + `![Image](${this.id.split("IMG_TAG+")[1]} =100x100)`;
});